title: Tyson Mote
email: tyson@bufio.net
description: >-
  Tyson is a software engineer from Portland, Oregon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bufio.net" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
